feature: support environ in ngx.pipe on mac
openresty/lua-nginx-module pull request #1882
Opened 2021-05-18 07:57 UTC by tzssangglass

I hereby granted the copyright of the changes in this pull request
to the authors of this lua-nginx-module project.

2021-05-18 08:53 UTC, spacewander approved these changes

2021-05-18 09:00 UTC, spacewander requested changes

2021-05-18 09:00 UTC, spacewander commented on src/ngx_http_lua_pipe.c
> +        if (execvpe(file, (char * const *) argv, (char * const *) environ)
Please fix the indent

2021-05-18 09:10 UTC, tzssangglass commented on src/ngx_http_lua_pipe.c
> +        if (execvpe(file, (char * const *) argv, (char * const *) environ)
update

2021-05-19 01:33 UTC, spacewander approved these changes

2021-06-10 10:14 UTC, doujiang24 approved these changes

2021-06-10 12:56 UTC, merged