feature: implemented keepalive pooling in 'balancer_by_lua*'. (#38)
openresty/lua-nginx-module pull request #1908
Opened 2021-08-18 05:43 UTC by zhuizhuhaomeng

Co-authored-by: Thibault Charbonnier <thibaultcha@me.com>

I hereby granted the copyright of the changes in this pull request
to the authors of this lua-nginx-module project.

2021-08-31 06:13 UTC, doujiang24 commented on src/ngx_http_lua_balancer.c
> +        p = ngx_snprintf(errbuf, *errbuf_size, "no request found");
why do we need this change?

2021-09-03 01:20 UTC, doujiang24 commented on src/ngx_http_lua_balancer.c
> +    u_char                         hostbuf[32];
better use a meaning full macro for the hardcode `32`.

And maybe host_data may be a better name? it's not actually a buffer.

2021-09-03 01:20 UTC, doujiang24 commented on src/ngx_http_lua_balancer.c
> +    u_char                         hostbuf[32];
And better add a comment for this field.
```
try to avoid allocating memory from the connection pool
```

2021-09-03 01:28 UTC, doujiang24 approved these changes

2021-09-03 16:10 UTC, xiaocang requested changes

2021-09-03 16:10 UTC, xiaocang commented on README.markdown
> +This directive was first introduced in the `v0.10.19.5` release.
typo here?
`v0.10.19.5` -> `v0.10.19`

2021-09-03 16:10 UTC, xiaocang commented on doc/HttpLuaModule.wiki
> +This directive was first introduced in the <code>v0.10.19.5</code> release.
Ditto

2021-09-03 16:10 UTC, xiaocang commented on src/ngx_http_lua_balancer.c
> +            p = ngx_snprintf(errbuf, *errbuf_size, "%s", url.err);
`errbuf` is undeclared before

2021-09-04 02:35 UTC, doujiang24 commented on src/ngx_http_lua_balancer.c
> +        if (ngx_handle_read_event(c->read, 0) == NGX_OK) {
```suggestion
        if (ngx_handle_read_event(c->read, 0) != NGX_OK) {
```

2021-09-04 02:35 UTC, doujiang24 commented on src/ngx_http_lua_balancer.c
> +            && name->len == item->host.len
maybe we should move these length compare expressions at the front?
I'm not sure if the C compiler is clever enough to do such optimizations.

2021-09-04 02:35 UTC, doujiang24 commented on src/ngx_http_lua_balancer.c
> +     * or $http_host; we have to strip it
better add an example of the `ssl name` value here.

2022-10-11 07:41 UTC, Triple-Z commented
Any update on this issue?

2024-07-01 06:43 UTC, merged

2024-07-02 08:36 UTC, tzssangglass commented
hi @zhuizhuhaomeng, we found an edge bug in the keepalive pool.

in short, in the balancer phase, when obtaining a connection from the upstream connection pool, the cached attribute of the peer connection is set to 1(`pc->cached = 1`;), indicating that the connection is obtained from the cache.

if an error occurs during the use of this connection, such as "upstream prematurely closed connection" the system will increase the tries attribute of the peer connection by executing `u->peer.tries++`.

tries represents the maximum number of attempts to connect to an upstream server. It equals the normal 1 try + set_more_tries.

the occurrence of `u->peer. tries++` is unexpected and it results in the actual retry count exceeding `set_more_tries`.

here is a reproduce test case:

```perl
# vim:set ft= ts=4 sw=4 et:

use Test::Nginx::Socket::Lua;
use Cwd qw(cwd);

log_level('info');
repeat_each(1);

plan tests => repeat_each() * (blocks() * 6);

my $pwd = cwd();

no_long_string();

check_accum_error_log();
run_tests();

__DATA__

=== TEST 1: sanity
--- http_config
    lua_shared_dict request_counter 1m;
    upstream my_upstream {
        server 127.0.0.1;
        balancer_by_lua_block {
            local balancer = require "ngx.balancer"

            if not ngx.ctx.tries then
                ngx.ctx.tries = 0
            end

            ngx.ctx.tries = ngx.ctx.tries + 1
            ngx.log(ngx.INFO, "tries ", ngx.ctx.tries)

            if ngx.ctx.tries == 1 then
                balancer.set_more_tries(5)
            end
            
            local host = "127.0.0.1"
            local port = 8090;

            local ok, err = balancer.set_current_peer(host, port)
            if not ok then
                ngx.log(ngx.ERR, "failed to set the current peer: ", err)
                return ngx.exit(500)
            end

            balancer.set_timeouts(60000, 60000, 60000)

            local ok, err = balancer.enable_keepalive(60, 100)
            if not ok then
                ngx.log(ngx.ERR, "failed to enable keepalive: ", err)
                return ngx.exit(500)
            end
        }
    }

    server {
        listen 0.0.0.0:8090;
        location /hello {
            content_by_lua_block{                
                local request_counter = ngx.shared.request_counter
                local first_request = request_counter:get("first_request")
                if first_request == nil then
                    request_counter:set("first_request", "yes")
                    ngx.print("hello")
                else
                    ngx.exit(ngx.HTTP_CLOSE)
                end
            }
        }
    }
--- config
    location = /t {
        proxy_pass http://my_upstream;
        proxy_set_header Connection "keep-alive";
        
        rewrite_by_lua_block {
           ngx.req.set_uri("/hello")
        }
    }
--- pipelined_requests eval
["GET /t HTTP/1.1" , "GET /t HTTP/1.1"]
--- response_body eval
["hello", qr/502/]
--- error_code eval
[200, 502]
--- error_log eval
qr/tries 7/
```

in this case:
1. the first request is normal. balancer creates a connection with the upstream and puts the connection into the balancer connection pool after the first request end
2. the second request, pulling a healthy connection from the balancer connection pool and using it, here would mark connection as cached:

	https://github.com/openresty/lua-nginx-module/blob/6738c3a3b0d62b98ff35acf7f7c4a191207da918/src/ngx_http_lua_balancer.c#L1480

 and the upstream shut down the connection by `ngx.exit(ngx.HTTP_CLOSE)`, this is 1 normal try.
3. enter the retry phase, the shutdown just upstream is marked by nginx as `NGX_HTTP_UPSTREAM_FT_ERROR`, and would enter the follow code:
```C
    if (u->peer.cached && ft_type == NGX_HTTP_UPSTREAM_FT_ERROR) {
        /* TODO: inform balancer instead */
        u->peer.tries++;
    }
```
https://github.com/nginx/nginx/blob/e734df6664e70f118ca3140bcef6d4f1750fa8fa/src/http/ngx_http_upstream.c#L4366-L4369

4. `u->peer.tries++` increases the retry times by one.

it seems that Nginx believes that a cached connection improperly closed upstream is not a real retry, so it compensates for a retry.

in the upstream shutdown scenario, this mechanism drains the connections in the balancer connection pool and tries as many times as set by `set_more_tries`.

this results in executing `balancer_by_lua_block` over `set_more_tries`.

2024-07-02 08:43 UTC, tzssangglass commented
one way to fix this is to change this mechanism and implement `notify` for `ngx_http_lua_balancer`, like this: https://github.com/Kong/openresty-patches-review/pull/1/files

the another way is not to handle it, we just need to know that it exists, and we can retrieve the `cached` of connection to determine whether the connection was obtained from the balancer connection pool.

2024-07-05 02:17 UTC, tzssangglass commented
cc @dndx

2024-07-07 15:14 UTC, zhuizhuhaomeng commented
@tzssangglass would you please prepare a patch for this issue?

2024-07-08 02:23 UTC, tzssangglass commented
I'd like to know which of the above fixes you prefer

2024-07-08 03:06 UTC, zhuizhuhaomeng commented
I prefer the first one(kong's implementation).