feature: added new ffi function ngx_http_lua_ffi_ssl_ciphers.
openresty/lua-nginx-module pull request #1958
Opened 2021-10-30 05:33 UTC by zhuizhuhaomeng

I hereby granted the copyright of the changes in this pull request
to the authors of this lua-nginx-module project.

2021-10-30 15:14 UTC, doujiang24 requested changes

2021-10-30 15:14 UTC, doujiang24 commented on src/ngx_http_lua_ssl_certby.c
> +        return NGX_ERROR;
should set the `err` here.

2021-10-30 15:14 UTC, doujiang24 commented on src/ngx_http_lua_ssl_certby.c
> +        return NGX_ERROR;
ditto should set the `err` here.

2021-10-31 08:10 UTC, doujiang24 reviewed
two more ideas:
1. we'd better pass a memory buffer pointer from Lua to reduce memory allocation in the connection pool. But the current implementation is also acceptable to me.
2. we can call `ngx_ssl_get_ciphers` in the `ngx_http_lua_ffi_ssl_ciphers` function if we decide to allocation memory from the connection pool to avoid coping code.

2021-10-31 10:48 UTC, zhuizhuhaomeng commented
> two more ideas:
> 
> 1. we'd better pass a memory buffer pointer from Lua to reduce memory allocation in the connection pool. But the current implementation is also acceptable to me.
> 2. we can call `ngx_ssl_get_ciphers` in the `ngx_http_lua_ffi_ssl_ciphers` function if we decide to allocation memory from the connection pool to avoid coping code.

I prefer the latter one because it is hard to decide the length of the buffer.

2021-11-01 00:18 UTC, doujiang24 approved these changes

2021-11-01 10:42 UTC, bjne commented
The output format of ssl_get_chipers is imho ineffective for what it is useful for. What I would like to get out is
perhaps a table (table could be passed as input for reuse) or just a int array of ciphers shared between client
and server.

2021-11-01 14:15 UTC, xiaocang approved these changes

2021-11-01 14:34 UTC, zhuizhuhaomeng commented
> The output format of ssl_get_chipers is imho ineffective for what it is useful for. What I would like to get out is perhaps a table (table could be passed as input for reuse) or just a int array of ciphers shared between client and server.

Can you be more specific about your application scenario?

2021-11-01 14:49 UTC, bjne commented
> > The output format of ssl_get_chipers is imho ineffective for what it is useful for. What I would like to get out is perhaps a table (table could be passed as input for reuse) or just a int array of ciphers shared between client and server.
> 
> Can you be more specific about your application scenario?

A common usecase where is probably to check if client supports EDCSA ciphers, and serve certs accordingly. Splitting/iterating/garbage collecting colon-separated strings here is omho less effective than returning uint32_t[]
of uint32_t SSL_CIPHER_get_protocol_id(const SSL_CIPHER *c);

Also, only the enabled ciphers (SSL_get_ciphers/SSL_get_client_ciphers) is more useful than also needing to know
what ciphers are actually enabled to make decision.

2021-11-02 00:00 UTC, zhuizhuhaomeng commented
> > > The output format of ssl_get_chipers is imho ineffective for what it is useful for. What I would like to get out is perhaps a table (table could be passed as input for reuse) or just a int array of ciphers shared between client and server.
> > 
> > 
> > Can you be more specific about your application scenario?
> 
> A common usecase here is probably to check if client supports EDCSA ciphers, and serve certs accordingly. Splitting/iterating/garbage collecting colon-separated strings here is less effective than returning uint32_t[] of uint32_t SSL_CIPHER_get_protocol_id(const SSL_CIPHER *c);
> 
> Also, only the enabled ciphers (SSL_get1_supported_ciphers/SSL_get_client_ciphers) is more useful than also needing to know what ciphers are actually enabled to make decision.

Would you please submit a PR?

2021-11-02 10:48 UTC, bjne commented
> > > > The output format of ssl_get_chipers is imho ineffective for what it is useful for. What I would like to get out is perhaps a table (table could be passed as input for reuse) or just a int array of ciphers shared between client and server.
> > > 
> > > 
> > > Can you be more specific about your application scenario?
> > 
> > 
> > A common usecase here is probably to check if client supports EDCSA ciphers, and serve certs accordingly. Splitting/iterating/garbage collecting colon-separated strings here is less effective than returning uint32_t[] of uint32_t SSL_CIPHER_get_protocol_id(const SSL_CIPHER *c);
> > Also, only the enabled ciphers (SSL_get1_supported_ciphers/SSL_get_client_ciphers) is more useful than also needing to know what ciphers are actually enabled to make decision.
> 
> Would you please submit a PR?

Yes, I can do that.

2021-11-03 11:05 UTC, bjne commented
> > > > > The output format of ssl_get_chipers is imho ineffective for what it is useful for. What I would like to get out is perhaps a table (table could be passed as input for reuse) or just a int array of ciphers shared between client and server.
> > > > 
> > > > 
> > > > Can you be more specific about your application scenario?
> > > 
> > > 
> > > A common usecase here is probably to check if client supports EDCSA ciphers, and serve certs accordingly. Splitting/iterating/garbage collecting colon-separated strings here is less effective than returning uint32_t[] of uint32_t SSL_CIPHER_get_protocol_id(const SSL_CIPHER *c);
> > > Also, only the enabled ciphers (SSL_get1_supported_ciphers/SSL_get_client_ciphers) is more useful than also needing to know what ciphers are actually enabled to make decision.
> > 
> > 
> > Would you please submit a PR?
> 
> Yes, I can do that.

Here is the RFC pull request: https://github.com/openresty/lua-nginx-module/pull/1962

2022-01-14 13:51 UTC, closed without merging