feature: expose the 'Last-Modified' response header as ngx.header["Last-Modified"].
openresty/lua-nginx-module pull request #1983
Opened 2021-12-26 15:34 UTC by zhuizhuhaomeng

I hereby granted the copyright of the changes in this pull request
to the authors of this lua-nginx-module project.

2021-12-30 15:08 UTC, xiaocang requested changes

2021-12-30 15:30 UTC, xiaocang approved these changes

2022-01-01 15:35 UTC, doujiang24 commented on src/ngx_http_lua_headers.c
> +        }
maybe we can return 0 here when the `last_modified < 0`? just for better performance.

2022-01-01 15:35 UTC, doujiang24 commented on src/ngx_http_lua_headers.c
> +        last_modified = r->headers_out.last_modified_time;
we should check if the `key_buf` is `Last-Modified-time`?

2022-01-02 14:41 UTC, doujiang24 commented on t/016-resp-header.t
> +=== TEST 96: Expose the 'Last-Modified' response header as ngx.header["Last-Modified"]
duplicated test name, better use a unique one.
Do you want to test the header is not existing?

2022-01-02 14:41 UTC, doujiang24 commented on src/ngx_http_lua_headers.c
> +
style: useless blank line.

2022-01-04 03:57 UTC, doujiang24 approved these changes

2022-01-04 05:14 UTC, merged