bugfix: the error message should use the first line rather than the last line of the code block when load lua code block failed.
openresty/lua-nginx-module pull request #2005
Opened 2022-02-08 08:06 UTC by zhuizhuhaomeng

I hereby granted the copyright of the changes in this pull request
to the authors of this lua-nginx-module project.

2022-02-08 19:50 UTC, agentzh requested changes

2022-02-08 19:50 UTC, agentzh commented on src/ngx_http_lua_directive.c
> +    start_line = lmcf->directive_line ? : cf->conf_file->line;
We should never use the GNU C language extension. Never. We should also add this check to the ngx-releng tool?

2022-02-09 03:51 UTC, agentzh approved these changes

2022-02-09 04:37 UTC, xiaocang approved these changes

2022-02-09 04:43 UTC, merged