Feature/add ssl trusted certificate
openresty/lua-nginx-module pull request #2329
Opened 2024-07-04 12:04 UTC by theweakgod

This mainly adds the ssl_trusted_certificate feature to avoid issues where CA authentication issued by secondary certificates cannot succeed in mTLS. Added the trusted_cert parameter option for verify_client.
I have made the corresponding modifications at the lua-resty-core:
https://github.com/openresty/lua-resty-core/pull/473

2024-07-07 03:37 UTC, zhuizhuhaomeng commented
Will you show us a detailed example of the mTLS failed

2024-07-07 04:14 UTC, theweakgod commented
> Will you show us a detailed example of the mTLS failed

The scenario is as follows: verify_client will send the subject names of all CA. However, we do not want to expose the root subject name, so verify_client only wants to send the subject names of the intermediate CA to the client. So we only set intermediate CA in verify_client, but this will cause the verification to fail because the root CA is not trusted.

We have tried configuring nginx ssl_trusted_certificate and simultaneously calling verify_client to send the intermediate CA, but found it doesn't work. After reading the source code, I discovered that verify_client overrides the cert->verify_store configured in nginx, and this operation is implicit in verify_client. So, I created this pull request.

This scenario can be resolved by configuring nginx as follows:

ssl_client_certificate client-server.crt;
ssl_trusted_certificate client-server-root.crt;
ssl_verify_depth 2;
ssl_verify_client on;

More details can be found in Test 13(140-ssl-c-api.t).

2024-07-08 14:59 UTC, zhuizhuhaomeng approved these changes

2024-07-08 15:01 UTC, zhuizhuhaomeng requested changes

2024-07-08 15:01 UTC, zhuizhuhaomeng commented on src/ngx_http_lua_ssl_certby.c
> +ngx_http_lua_ffi_ssl_verify_client(ngx_http_request_t *r, void *ca_certs,
please remove the trailing space

2024-07-08 15:01 UTC, zhuizhuhaomeng commented on src/ngx_http_lua_ssl_certby.c
> +
remove the extra blank line

2024-07-08 15:14 UTC, theweakgod commented on src/ngx_http_lua_ssl_certby.c
> +ngx_http_lua_ffi_ssl_verify_client(ngx_http_request_t *r, void *ca_certs,
done

2024-07-09 04:10 UTC, zhuizhuhaomeng approved these changes

2024-07-09 04:10 UTC, merged